In [1]:
from numpy import *

def createDataset():
    group = array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels = ['A','B','C','D']
    return group, labels
a, b = createDataset()
print(a)
print(b)

[[1.  1.1]
 [1.  1. ]
 [0.  0. ]
 [0.  0.1]]
['A', 'B', 'C', 'D']


In [2]:
tv = [0.2,0.3]
tile(tv, (4,1))

array([[0.2, 0.3],
       [0.2, 0.3],
       [0.2, 0.3],
       [0.2, 0.3]])

In [3]:
diff = tile(tv, (4,1)) - a
print(diff)

[[-0.8 -0.8]
 [-0.8 -0.7]
 [ 0.2  0.3]
 [ 0.2  0.2]]


In [4]:
print(a.shape[0], a.shape[1])

4 2


In [5]:
data = array([2,5,7,3,4,1])
data.sort()
print(data)

[1 2 3 4 5 7]
